### ISSUE TITLE
Memory leak on empty foreach script

### ISSUE THREAD

**Issue by jonpas** [synixebrett/HEMTT#101]
**HEMTT Version:** `0.6.0` (stable)
**Project:** ACE3 (only `main`)

**Description:**

Running ACE3 with a releasebuild script which just echoes all the targets causes a memory leak and infinite run of a script.

**Steps to reproduce:**

- Setup a script, eg.:
```
releasebuild = [
    "!launchableoptionals"
]

[scripts]
    [scripts.launchableoptionals]
    steps = [
        "echo \"{{target}} | {{addon}}\""
    ]
    show_output = true
    foreach = true
```
- Run with `hemtt build --release -f main`
- Experience infinite run of `launchableoptionals` script and memory leak

**Additional information:**

/

**HEMTT Output:**

Stuck at `Script launchableoptionals`.

**Comment by jonpas** [comment]
Further testing shows it gets stuck on one of the PBOs, because they were not built. So instead of going through what was actually build in the script, it runs for all that are in the project?

**Comment by jonpas** [comment]
Looks like it happens even if you use eg.:
```
 "if [ $(dirname optionals/x) == 'optionals' ]; then echo yes; fi"
```
Mind, no templating used at all.

**Comment by synixebrett** [comment]
Can't reproduce with Bash 4.4.23 on Windows 10

**Comment by jonpas** [comment]
I can't reproduce anymore either.
