### ISSUE TITLE
target template can't be used multiple times in script

### ISSUE THREAD

**Issue by jonpas** [synixebrett/HEMTT#102]
**HEMTT Version:** `0.6.0` (stable)
**Project:** ACE3

**Description:**

`{{target}}` template in scripts can't be used more than once. `{{addon}}` works fine multiple times.

**Steps to reproduce:**

- Add script with step `"echo {{target}} {{target}}"`
- Run HEMTT
- Observe being stuck at script with memory leak

**Additional information:**

/

**HEMTT Output:**

/

**Comment by synixebrett** [comment]
Can't reproduce, closing in favor of #101
