### ISSUE TITLE
Feature request: Add an option to change MAINPREFIX in project configuration

### ISSUE THREAD

**Issue by veteran29** [synixebrett/HEMTT#121]
**Description:**

Could you consider adding an option to change `#define MAINPREFIX z` via project configuration file?

Change of this value should also change paths in includes and pboprefixes etc.

**Comment by synixebrett** [comment]
Once templating is done this could be achieved through that, otherwise I don't think this is worth adding vs the time it takes to change the prefix manually.

**Comment by veteran29** [comment]
Makes sense. I'll wait for it then.

**Comment by Katalam** [comment]
Why should you even change the MAINPREFIX? Why not leave all mods in x? Or z? What's the difference?
