### ISSUE TITLE
unquoted string warning

### ISSUE THREAD

**Issue by s-trooper** [synixebrett/HEMTT#169]
**HEMTT Version:** `0.6.1` (stable)
**Project:** local testing

**Description:**

I've got i warning in default hemtt created project, it is from armake2 but related to template generated here.
```
In file addons\main\config.cpp:4: warning: String value "main" is not quoted properly. [unquoted-string]
```

**Steps to reproduce:**

1. hemtt create 
...
2. hemtt build

**Additional information:**

I am quite sure the warning can be ignored but for a beginner like me it's confusing ... 

**HEMTT Output:**

````
  Building 1
In file addons\main\config.cpp:4: warning: String value "main" is not quoted properly. [unquoted-string]
In file addons\main\config.cpp:10: warning: String value "0.1.0.0" is not quoted properly. [unquoted-string]
     Built 1
  Finished test
````

**Comment by synixebrett** [comment]
This is an issue with the [CBA](/cba_team/CBA_a3) macros, not HEMTT or armake2 directly.

**Comment by s-trooper** [comment]
Oh, i thought the macro was part of this project. Ok, closed :)
