### ISSUE TITLE
Wrong directory file tree for optionals folder when releasing

### ISSUE THREAD

**Issue by DerZade** [synixebrett/HEMTT#184]
**HEMTT Version:** ` 0.6.2-0f940c5fb17f4ebec723dbdbb0c8b63dc072135e`

**Project:** https://github.com/DerZade/grad_minui/tree/484717e93a8908ac07c1872ce3f5d488def3c322

**Description:**
When building a release with optionals the output directory of the optionals is wrong.

In my project I have one optional `compat_ace` and the built pbo can be found here:
`./releases/0.6.2.0/@grad_minui/optionals/@grad_minui_compat_ace/addons/grad_minui_compat_ace.pbo`
instead of the expected output dir:
`./releases/0.6.2.0/@grad_minui/optionals/grad_minui_compat_ace.pbo`

So HEMTT creates another mod-file tree for the optional within the optionals folder of the main mod.

**Steps to reproduce:**
- Build a release incl. optionals with HEMTT (executables can be found in the tools dir)
- e.g. `./tools/hemtt.exe build --release --opts=all`

**HEMTT Output:**
```
 Preparing release v0.6.2.0
  Building 8
     Built 8
    Signed 8
  Starting Release Build
   Utility zip
 Archiving grad_minui_0.6.2.0.zip
 Archived  grad_minui_0.6.2.0.zip
      Done zip
  Finished Release Build
  Finished grad_minui v0.6.2.0
```

**Comment by synixebrett** [comment]
https://synixebrett.github.io/HEMTT/#/project?id=folder_optionals
