### ISSUE TITLE
Running build fails

### ISSUE THREAD

**Issue by Reidond** [synixebrett/HEMTT#207]
**HEMTT Version:** `0.7.0-ee6a77b` dev
**Project:** Local project

**Description:**

Can't build addons but can create them 

**Steps to reproduce:**

- Run `hemtt build`

**Additional information:**

Every other command also fails with same issues

**HEMTT Output:**

[Pastebin](https://pastebin.com/e1Ws1hgN)

**Comment by synixebrett** [comment]
This is an error with the template, the template variables need to be lowercase. Unfortunately, there is no way to support both cases. I know you got this from HEMTT/CBA, I do apologize as no one had actually used the template system in 0.7.0 yet and it was still undocumented. If you do a find and replace for `MAINPREFIX` to `mainprefix` and `PREFIX` to `prefix` that should fix the issue for you. I will fix this is the template.

**Comment by Reidond** [comment]
Ok, now there is a new error:
```
Clean                                                                                                                               Checks         [00:00:00] [##############################] [1|1]                                                                    Prebuild       [00:00:00] [##############################] [1|1]
error: Unable to preprocess `script_component.hpp`
    File "\z\mm\addons\main\script_mod.hpp" included from "\\?\C:\Users\reido\Documents\MyMod\addons\main\script_component.hpp" not found.

error: Unable to build `addons\main`
```
