### ISSUE TITLE
Feature Request: Apply filter before building the pbo

### ISSUE THREAD

**Issue by Katalam** [synixebrett/HEMTT#226]
I personally add all my project related files into the project structure. Like a `.psd` I used to create a texture, is right next to the `.paa`/`.png` file.
But as soon as I build the project I don’t want to have this `.psd` file in my pbo. Is it possible like mikero‘s or BI‘s tools to apply a filter before the actual build process? Like I want only `.sqf`, `.cpp`, `.hpp`, `.paa`, … to be copied into the pbo and not just all files?

**Comment by synixebrett** [comment]
https://synixebrett.github.io/HEMTT/#/project?id=exclude
