### ISSUE TITLE
Can't start hemtt 0.7.2 on windows

### ISSUE THREAD

**Issue by bux** [synixebrett/HEMTT#233]
**HEMTT Version:** 0.7.2

**HEMTT Output:**
![image](https://user-images.githubusercontent.com/1235520/71148701-a330a100-222c-11ea-9201-e386202ce197.png)

That when starting directly or nothing when called from powershell

![image](https://user-images.githubusercontent.com/1235520/71148731-b3e11700-222c-11ea-94e0-23fc1ab07210.png)

**Comment by ColdEvul** [comment]
Get this as well.

**Comment by bux** [comment]
Fixed with https://github.com/synixebrett/HEMTT/releases/tag/v0.7.3
