### ISSUE TITLE
Binarizer not found warning not displayed on Linux

### ISSUE THREAD

**Issue by jonpas** [synixebrett/HEMTT#265]
**HEMTT Version:** `0.7.4` (stable)
**Project:** Any

**Description:**

Output some information about used or unused binarizer (Windows/Linux) as is the case with armake2.

**Steps to reproduce:**

- Build

**Additional information:**

N/A

**HEMTT Output:**

N/A

**Comment by synixebrett** [comment]
This should already be the case

**Comment by synixebrett** [comment]
`hemtt build --debug` will also tell you where the binarize executable was found

**Comment by jonpas** [comment]
Debug does indeed, but it's crowded in a lot of other debug data. I think that's pretty important to show to the user and should be displayed in normal mode. At least if it's binarizing or not binarizing.

**Comment by synixebrett** [comment]
```rs
if match armake2::find_binarize_exe() {
    Ok(p) => {
        debug!("binarize found at {:?}", p);
        p.exists()
    }
    Err(_) => false,
} {
    true
} else {
    warnmessage!("Unable to locate binarize.exe", "Files will be packed as is");
    false
};
```

It prints a message if binarize is not found

**Comment by jonpas** [comment]
I am not seeing this anywhere.

```
if {
    // code
} {
    true
} else {
    // code
}
```
How does this work?

**Comment by synixebrett** [comment]
```rust
match armake2::find_binarize_exe() {
    Ok(p) => {
        debug!("binarize found at {:?}", p);
        p.exists()
    }
    Err(_) => false,
}
```

`find_binarize_exe` returns a `Result<Path, Error>`, the match is used to get the path if it is Ok. If it is Ok it calls `p.exists()` which will return a boolean. The `find_binarize_exe` was unable to find the executable then it ignores the error and just returns false. That result boolean is then what is fed into the wrapping if statement.

**Comment by jonpas** [comment]
Alright, I see.

And I also see why it doesn't work. That `match` will never run if this is not on Windows. Rust does lazy evaluation, so as soon as `cfg!(windows)` is `false`, it stops evaluating that condition, meaning `match find_binarize_exe()` will never run and thus never print an error.

#274
