### ISSUE TITLE
UNC Network paths no longer supported

### ISSUE THREAD

**Issue by jonpas** [synixebrett/HEMTT#266]
**HEMTT Version:** `0.7.4` (stable)
**Project:** Any

**Description:**

Building a mod located on a UNC path fails.

**Steps to reproduce:**

- Build a mod located on a UNC path.

**Additional information:**

Requires network shared drive.

**HEMTT Output:**

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PATH(IOPathError { source: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }, path: "UNC\\10.0.2.2\\Work\\Arma 3\\Mods\\TheseusServices\\optionals\\weapons_hlc\\script_component.hpp" })', src\libcore\result.rs:1165:5
```

**Comment by synixebrett** [comment]
> no longer supported

Was this working with a previous version of HEMTT?

**Comment by jonpas** [comment]
Yes, it worked fine until I switched to 0.7.3(+).

**Comment by jonpas** [comment]
[0.6.2]() works correctly:

Path in 0.6.2:
```
\\?\UNC\10.0.2.2\Work\Arma 3\Mods\CBA_A3
```
same path in 0.7.2+ (presumably):
```
UNC\\10.0.2.2\Work\Arma 3\Mods\CBA_A3
```

**Comment by jonpas** [comment]
https://github.com/synixebrett/HEMTT/blob/792223aac803a0d85b235d319e75e7ff691dda76/src/files.rs#L28

This breaks it as shown in the above comment (removes leading `\\?\`). Why was this added?
