### ISSUE TITLE
HEMTT binary used as configuration file if same name

### ISSUE THREAD

**Issue by jonpas** [synixebrett/HEMTT#267]
**HEMTT Version:** `0.7.4` (stable)
**Project:** Any

**Description:**

Having a Linux HEMTT binary `hemtt` in project root next to configuration file `hemtt.toml` causes HEMTT to find itself and fail instead of finding the proper file with the extension.

**Steps to reproduce:**

- Name HEMTT binary `hemtt` and place it next to `hemtt.toml` configuration file.
- Try building the mod.

**Additional information:**

N/A

**HEMTT Output:**

```
$ ls
addons hemtt* hemtt.toml ...
$ hemtt build
configuration file "/home/jonpas/Data/Work/Arma 3/Mods/TheseusServices/hemtt" is not of a registered file format
```

**Comment by synixebrett** [comment]
This is actually going to not be an elegant fix, it may just be "Don't name it `hemtt` and put it in your project folder.

**Comment by jonpas** [comment]
It's named hemtt when you download it and documentation says to put it in the project folder. That would literally put it upside down to how it always worked.

**Comment by synixebrett** [comment]
Yeah, I'm aware and it's really not ideal. The config library just looks for `hemtt*`, one way to fix this would be to deprecate JSON and only look for toml files from now on.

**Comment by jonpas** [comment]
No way to look for both separately? Like find `toml`, if not found, find `json`.
