### ISSUE TITLE
Please add `hemtt build --watch` option

### ISSUE THREAD

**Issue by bovine3dom** [synixebrett/HEMTT#28]
I'd like HEMTT to rebuild every time I change a relevant file. On linux this is easy: `ls ** | entr hemtt build`. On Windows, it is much more of a pain in the bum.

Rust has some nice looking libraries that would do the bulk of the work for you, e.g, https://github.com/francesca64/hotwatch.

Thanks!

**Comment by jonpas** [comment]
That's not as useful in the context of Arma though.

For SQF, you have file patching, which doesn't need rebuilding at all.
For config, you have to restart anyways for majority of the things (except dev-branch with that merge config command which is far from perfect).

**Comment by bovine3dom** [comment]
Yeah, you have to restart ArmA, which is why it's really annoying when I forget to rebuild stuff after I've changed it :)

**Comment by jonpas** [comment]
You can't rebuild PBOs while Arma is running, as it places a lock on them.

**Comment by synixebrett** [comment]
I'm going to close since I don't think HEMTT will need this functionality. As jonpas said it isn't very useful with Arma.
