### ISSUE TITLE
Template utility doesn't work

### ISSUE THREAD

**Issue by DerZade** [synixebrett/HEMTT#280]
**HEMTT Version:** `0.7.4` (although `--version` logs `0.7.3` 😂)

**Description:**
Template utility throws error when used.

**Steps to reproduce:**
- change into your project
- execute `<PATH TO HEMTT>/hemtt.exe template {{name}}`

**HEMTT Output:**
```
./tools/hemtt.exe template {{name}}
error: Found argument '{{name}}' which wasn't expected, or isn't valid in this context

USAGE:
    hemtt.exe template [FLAGS] [OPTIONS] [SUBCOMMAND]

For more information try --help
```

**Comment by jokoho48** [comment]
The Template system is currently in a Major Restructure and is not in a working state https://github.com/synixebrett/HEMTT/pull/248. Use the [ace arma-project-template](https://github.com/acemod/arma-project-template) instead

**Comment by DerZade** [comment]
> The Template system is currently in a Major Restructure and is not in a working state #248. Use the [ace arma-project-template](https://github.com/acemod/arma-project-template) instead

I think you misunderstood what I'm trying to do :sweat_smile:. I don't want to have "project template", instead I'm asking about [this templating utility](https://synixebrett.github.io/HEMTT/#/utilities?id=template), which can be used to replace handlebar templates with their values in the `hemtt.toml` / `hemtt.json`.
So [this kind of templating](https://synixebrett.github.io/HEMTT/#/templating) is meant ^^

**Comment by jokoho48** [comment]
no that is correct that the templating system is currently in a major rewrite and is not in a working state. #248 is the PR that should finish the restructure and the Wiki is heavily out of date.

**Comment by synixebrett** [comment]
This is now back as `hemtt var` to avoid confusion with HEMTT's WIP template system
