### ISSUE TITLE
File modifications not respected

### ISSUE THREAD

**Issue by jonpas** [synixebrett/HEMTT#300]
**HEMTT Version:** `0.8.0-dev` (53bcb953c65523060241cf81f4d3432fc32cacc0)
**Project:** Any

**Description:**

File modifications or `modtime` does not seem to be respected, every `hemtt build` rebuilds all PBOs, even if they weren't changed. On both Linux and Windows.

**Steps to reproduce:**

Run `hemtt build` twice in a row.

**Additional information:**

/

**HEMTT Output:**

/

**Comment by synixebrett** [comment]
I am definitely not having this issue, we'll need more info to try to find this one

**Comment by jonpas** [comment]
Can confirm fix.
