### ISSUE TITLE
Template Helper - Git

### ISSUE THREAD

**Issue by jonpas** [synixebrett/HEMTT#32]
Utility that retrieves current git commit hash:
- from `git` binary if available
- from `.git` folder if available

Ref.: [make.py](https://github.com/acemod/ACE3/blob/191c4fb694b80337c35a36be369b62c634f0e079/tools/make.py#L693)

Should support retrieving it as truncated (to N characters) for use in configurable options.

**Comment by synixebrett** [comment]
I would rather look at using a git library for rust. Preferable one that has parity support for both Windows and Linux. This will make expanded HEMTT interaction with git easier in the future and will potentially provide more stability than a solution we create ourselves.

**Comment by jonpas** [comment]
There is [git2](https://docs.rs/git2/0.8.0/git2/), will test it.
