### ISSUE TITLE
Clearing releases/ will cause the privatekey to be lost

### ISSUE THREAD

**Issue by synixebrett** [synixebrett/HEMTT#34]
Currently clearing all releases will cause the privatekey to be lost since it is stored in the releases/ folder after being generated.

**Comment by jonpas** [comment]
That's not a bug, but by design (mine at least). It gets generated with each release anyways.

We haven't had a same private key ever in CBA/ACE3, it's even safer that way and you don't have to rely on it at all.

**Comment by synixebrett** [comment]
Alright, I was under the impression the private key should be kept and reused in between releases.
