### ISSUE TITLE
Can't skip specified addons

### ISSUE THREAD

**Issue by synixebrett** [synixebrett/HEMTT#36]
`./hemtt build spectator,zeus --skip spectator`
Spectator will still be built.

While something like this shouldn't really ever be ran, we should at least print a warning. Interested in @jonpas's opinion on if it should still be skipped or not.

**Comment by bovine3dom** [comment]
In my experience, the rightmost flag usually takes precedence so that you can have a shell alias that contains some flags which can be overridden.

**Comment by jonpas** [comment]
Agreed with @bovine3dom.

**Comment by synixebrett** [comment]
I don't see a way to know the order they were entered with docopt
