### ISSUE TITLE
`rustfmt` as a pre-commit hook?

### ISSUE THREAD

**Issue by bovine3dom** [synixebrett/HEMTT#38]
E.g, https://github.com/google/tarpc/blob/master/hooks/pre-commit

We do something similar in another project I work on. It works rather well for ensuring that everyone sticks to the same code style.

**Comment by jonpas** [comment]
rustfmt is sometimes really weird, but if that's the Rust standard = :+1:.

**Comment by jonpas** [comment]
Closed by #77:
> I can't see any nice way of distributing pre-commit hooks, so I gave up on that idea.
