### ISSUE TITLE
Building specific addons is unintuitive

### ISSUE THREAD

**Issue by bovine3dom** [synixebrett/HEMTT#40]
Based on the help, I tried:

```
hemtt build weapon_shotgun object_fob object_crates
hemtt build --addons weapon_shotgun object_fob object_crates
hemtt build --addons weapon_shotgun,object_fob,object_crates
hemtt build --addons="weapon_shotgun,object_fob,object_crates"
hemtt build weapon_shotgun, object_fob, object_crates
hemtt build "weapon_shotgun,object_fob,object_crates"
```

The last one worked. I think the first is the most intuitive. Space separated variables is what most CLIs use. Is this a limitation of docopts?

The `--addons` option that's listed in the help doesn't seem to do anything.

**Comment by synixebrett** [comment]
I'll remove the `--` from `--addons`.

The reason it uses commas is because we have to for `--skip` and `--opts` due to docopts limitations. I did `addons` the same way for consistency within HEMTT.

**Comment by bovine3dom** [comment]
Somewhat tangential: I still don't understand `--addons`. What is it supposed to do?

`hemtt addon` creates an addon folder from a template. That's probably a bad name, especially if you're going to have `hemtt addons` too.

How about `hemtt init [--cba]`, and then repurposing `hemtt create` to create the listed addons from the template?

**Comment by synixebrett** [comment]
We aren't going to have a command `hemtt addons` if that is what you mean. It will just be `hemtt build [addons]` to be used like `hemtt build zeus,medical,hearing`
