### ISSUE TITLE
Build fails on windows

### ISSUE THREAD

**Issue by synixebrett** [synixebrett/HEMTT#50]
**HEMTT Version:** d4780bdba7ab85038e9a2f10eab86a267ab76741
**Project:** https://github.com/synixebrett/diwako_dui

**Description:**
armake is throwing a not found error for includes

**Steps to reproduce:**

- `hemtt build` on Windows 10

**HEMTT Output:**

```
error: Failed to build PBO:
Failed to parse config:
Failed to preprocess config:
Failed to preprocess include "script_component.hpp":
File "\z\diwako_dui\addons\main\script_mod.hpp" included from "\\?\C:\Users\Brett\Desktop\diwako_dui\addons\radar\script_component.hpp" not found.
```

**Comment by synixebrett** [comment]
Works with other mods I have on my windows machine, just not this one. I couldn't find any differences between them. I think this might be an armake2 issue.

**Comment by jokoho48** [comment]
armake2 builds it fine without crashes but it throws 2 warnings
```
$ .\armake2.exe build -i "include" .\addons\main\ dui_main.pbo
$ In file .\addons\main\config.cpp:4: warning: String value "main" is not quoted properly. [unquoted-string]
$ In file .\addons\main\config.cpp:12: warning: String value "1.4.1.2" is not quoted properly. [unquoted-string]
$  .\armake2.exe build -i "include" .\addons\radar\ dui_radar.pbo
$ In file .\addons\radar\config.cpp:4: warning: String value "radar" is not quoted properly. [unquoted-string]
$ In file .\addons\radar\config.cpp:10: warning: String value "1.4.1.2" is not quoted properly. [unquoted-string]
```

**Comment by jokoho48** [comment]
as an addition, my local version builds also fine with HEMTT

**Comment by synixebrett** [comment]
I was never able to figure out what was causing this, it only happened with that particular mod on that particular Windows VM.

**Comment by synixebrett** [comment]
I have now encountered another mod on my machine that is failing to build with the same error related to not being found.

**Comment by synixebrett** [comment]
Haven't encountered this in a while now, closing. Reopen if you encounter this issue.
