### ISSUE TITLE
Look up recursively for project file

### ISSUE THREAD

**Issue by bovine3dom** [synixebrett/HEMTT#55]
`git` has trained me that I can run tools anywhere within a project. I'd like to be able to do this with HEMTT too. It should be as simple as looking up recursively until one finds a HEMTT project file or finds root / some directory it can't access.

**Comment by synixebrett** [comment]
This kinda depends on #26, atleast for Windows.

It isn't that hard to implement, just not that useful without global installation right now. Again, this is simple to solve on linux if you don't mind using `/usr/bin/` or `$HOME/.local/bin`.

**Comment by bovine3dom** [comment]
Hmm, it only depends on #26 if users can't figure out how to put stuff on their path. It's pretty trivial in Windows via the GUI.
