### ISSUE TITLE
Remove leading '_' sign on PBOs if prefix parameter is empty in JSON config.

### ISSUE THREAD

**Issue by severgun** [synixebrett/HEMTT#71]
**HEMTT Version:** `0.5.1` (stable)
**Project:** None

**Description:**

Remove leading '_' sign if prefix parameter is empty in JSON config.
This will allow using HEMTT to build repo of mixed addons without prefexing each pbo.

**Steps to reproduce:**

- Create folders addons/abc_mod, addons/defg_mod
- Create hemtt.json with prefix=""
- Build
- _abc_mod.pbo _defg_mod.pbo

**Comment by jonpas** [comment]
but what's your prefix inside the PBO then? This doesn't look safe.

**Comment by severgun** [comment]
$PBOPREFIX$ file

**Comment by synixebrett** [comment]
This should at least be a warning, but no prefix seems unusual and isn't good practice. I don't think it shouldn't be allowed with HEMTT, but we should definitely yell at them.

**Comment by severgun** [comment]
May be you should not allow that and throw ERROR.
Then I will use makefile+armake2 (even if makefile syntax was made by aliens for predators)
Current silent behavior looks bad.

**Comment by synixebrett** [comment]
I don't think it should be prohibited and result in an error. There is nothing about it that would cause it not to work, it is just highly unusual and bad practice.

I think an unsilenceable big warning basically saying "this is bad and you should really not be doing this! go to [link] to learn why and how to fix this error"
