### ISSUE TITLE
Template Helpers - Warning/Error on missing param

### ISSUE THREAD

**Issue by jonpas** [synixebrett/HEMTT#73]
Template helpers require parameters, print an error or warning when they are missing.

**Comment by synixebrett** [comment]
This should be thrown by handlebars and handled by our `unwrap_or_print`. What scenario are you encountering where no error / warning is thrown?

**Comment by jonpas** [comment]
If you write `{{date}}` it will just be empty. Because it expects a chrono specifier.

**Comment by synixebrett** [comment]
Ah I see, that is valid handlebars so yeah we will need to add warnings to `git` and `date`.
