### ISSUE TITLE
HEMTT Clean fails with error when no optionals folder exists

### ISSUE THREAD

**Issue by DerZade** [synixebrett/HEMTT#95]
**HEMTT Version:** Commit `7137954`
**Project:** https://github.com/DerZade/grad_slinghelmet/tree/hemtt

**Description:**
`hemtt clean` fails and throws an error when no `optionals` exists. The job works fine after adding an `optionals` directory (even when empty).

**Steps to reproduce:**
- Open a project without an `optionals` directory
- Run `hemtt clean`

**Additional information:**

**HEMTT Output:**
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "Das System kann den angegebenen Pfad nicht finden." }', src\libcore\result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace. 
```
![img](https://i.imgur.com/wiS5Wio.png)

**Comment by jonpas** [comment]
https://github.com/synixebrett/HEMTT/blob/71379549b8d2eecc16af211647ca06c14075eee0/src/main.rs#L296 doesn't check if it exists.
